### ISSUE TITLE
Why not pymol 2.2?

### ISSUE THREAD

**Issue by churnikov** [pegi3s/dockerfiles#3]
Hello!

I'd like to ask you, why don't you use pymol 2.2? Were there any technical troubles which stopped you?

I'd really like to know, because my colleagues would like to use 2.2, but I can't find any images with this version.

**Comment by hlfernandez** [comment]
Hello,

We created the image using 1.8.4.0 because that is the package version available in Ubuntu 18.04. We can easily create a new image for pymol 2.3.0. Is that version suitable to you? 

Regards,

          Hugo.

**Comment by churnikov** [comment]
Yes, that would have been very nice))

My teammates would really appreciate it. And it would be an icing on the cake if you would use py38 instead of py27 c:

**Comment by hlfernandez** [comment]
Alright, I have just uploaded a new Docker image with the _2.3.0_ tag (which is also the _latest_). Pull it with _docker pull pegi3s/pymol:2.3.0_ and tell us if it is working fine. Thank you for your interest in our project.

**Comment by churnikov** [comment]
Everything looks good!
Thank you very much for your quick help and responses))

**Comment by hlfernandez** [comment]
Thank you for your feedback, since it is working I close this issue.
