### ISSUE TITLE
How to run pymol on macOS?

### ISSUE THREAD

**Issue by churnikov** [pegi3s/dockerfiles#4]
Hello!

I'd like to know if it's possible to add instructions on how to run pymol in visual mode on macos?

**Comment by hlfernandez** [comment]
I am not sure if the mechanism for Linux also works in MacOS. We will try to have a look at this issue.

**Comment by Jorge-Vieira** [comment]
One way around would be to use the Virtual Box option (https://www.virtualbox.org/wiki/Downloads) that can be installed on MacOS systems and use the OVA file we provide at https://pegi3s.github.io/dockerfiles/ where Docker is already installed, and follow the instructions we give for Linux operating systems. While running Dockers images this way may have some limitations, depending on what you want to do, for the pymol Docker image this is not the case.
