### ISSUE TITLE
Not running on docker. 

### ISSUE THREAD

**Issue by kghimire09** [pegi3s/dockerfiles#6]
Hi, I have been trying to use your docker image on my docker file but it does not run. I am trying to use picard tools and gatk but I says that I may need to login? Could you please help me with this? For bwa it says E: The repository 'http://security.ubuntu.com/ubuntu disco-security Release' does not have a Release file.
Thank you

**Comment by hlfernandez** [comment]
Can you copy and paste the commands and the outputs you get?
